FROM golang:latest AS build
WORKDIR /go/src/github.com/loqutus/O-1
COPY . ./
RUN make get
RUN make build

FROM arm64v8/alpine:latest
WORKDIR /
COPY --from=build /go/src/github.com/loqutus/O-1/bin/o1-client-linux /usr/bin/o1-client
ENTRYPOINT ["/usr/bin/o1-client", "upload", "/usr/bin/o1-client", "--host", "o1"]
EXPOSE 6969