on: [push, pull_request]
name: test
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Setup Minikube
      uses: manusa/actions-setup-minikube@v2.4.2
      with:
       minikube version: 'v1.24.0'
       kubernetes version: 'v1.23.0'
    - name: make
      run: make docker docker_run etcd test