on: [push, pull_request]
name: test
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.17.6'
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: start minikube
      id: minikube
      uses: medyagh/setup-minikube@master
    - name: make
      run: eval $(minikube docker-env) && make 
    - name: logs
      run: make logs
      if: always()
    timeout-minutes: 10