on: [push, pull_request]
name: test
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.17.6'
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: run etcd
      run: |
        ETCD_VER=v3.5.2\
        GOOGLE_URL=https://storage.googleapis.com/etcd\
        GITHUB_URL=https://github.com/etcd-io/etcd/releases/download\
        DOWNLOAD_URL=${GOOGLE_URL}\
        mkdir -p /tmp/etcd-download-test\
        curl -L ${DOWNLOAD_URL}/${ETCD_VER}/etcd-${ETCD_VER}-linux-amd64.tar.gz -o /tmp/etcd-${ETCD_VER}-linux-amd64.tar.gz\
        tar xzvf /tmp/etcd-${ETCD_VER}-linux-amd64.tar.gz -C /tmp/etcd-download-test --strip-components=1\
        rm -f /tmp/etcd-${ETCD_VER}-linux-amd64.tar.gz\
        ALLOW_NONE_AUTHENTICATION=yes ETCD_ADVERTISE_CLIENT_URLS=http://0.0.0.0:2379 ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379 /tmp/etcd-download-test/etcd &
    - name: debug
      run: curl -v -L http://127.0.0.1:2379/version
    - name: make
      run: make get docker docker_run test
    - name: logs
      run: make docker_logs
      if: always()
          
          